spring:
    application:
        name: inventory-service
    cloud:
        config:
            profile: dev
    config:
        import: configserver:http://localhost:8888
management:
    endpoints:
        web:
            exposure:
                include: "*"
    tracing:
        sampling:
            probability: 1.0
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans